name: Build And Push
on:
  push:
    branches:
      - master
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment Variable
        id: vars
        run: echo "::set-output name=timestamp::$(date "+%Y%m%d")"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: |
          mvn clean install -U -Dmaven.test.skip=true
          
      - name: Set up resource
        run: |
          cp ${{ github.workspace }}/target/*.jar ${{ github.workspace }}/docker/
          cp ${{ github.workspace }}/config.cfg ${{ github.workspace }}/docker/
          cd ${{ github.workspace }}/docker/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          # file: Dockerfile
          platforms:  |
            linux/arm
            linux/arm64
            linux/amd64
          tags: |
            fansys/zkui:latest
            fansys/zkui:${{ steps.vars.outputs.timestamp }}
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
